### ISSUE TITLE
Task 5: Implement core features in the app

### ISSUE THREAD

**Issue by GLVSKiriti** [joeyyy09/truflow#22]
### `Task 5:`

Implement core features in the app. This includes:

- [ ] Discovering peers and knowledge of their online/offline status.
- [ ] Browsing files (and optionally, folders) available with online peers.
- [ ] Download available files when provider peers are online.

**Comment by GLVSKiriti** [comment]
cc @joeyyy09 @Satya-Saketh
